apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  application.properties: |-
    # server properties
    server.port=10001

    # spring properties
    spring.application.name=commonservice
    spring.banner.location=classpath:application-banner.txt

    # datasource properties
    spring.datasource.url=jdbc:mysql://commonservice-mysql.springk8s:3306/appk8s?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    spring.datasource.username=appuser
    spring.datasource.hikari.schema=appk8s
    
    # hibernate properties
    spring.jpa.show-sql=true
    spring.jpa.properties.hibernate.format_sql=true
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.open-in-view=false
    
    # flyway properties
    spring.flyway.enabled=true
    spring.flyway.user=root
    spring.flyway.locations=classpath:db
    spring.flyway.validate-on-migrate=true
    spring.flyway.default-schema=appk8s

    # logging properties
    logging.level.org.flywaydb=DEBUG

    # internal properties
    randommer.api.header.key.name=x-api-key
    randommer.api.header.key.value=d36b34e221ea4d0e894dc9fd97a9e2a3
    randommer.api.url=https://randommer.io
    randommer.api.endpoint.generate-phone=/api/Phone/Generate
    randommer.api.endpoint.validate-phone=/api/Phone/Validate
