apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.commonservice.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.labels" . | nindent 8 }}
    spec:
      {{- if .Values.commonservice.imagePullSecrets.enabled }}
      imagePullSecrets:
        - name: {{ .Values.commonservice.imagePullSecrets.name }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.commonservice.image.repository }}:{{ .Values.commonservice.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.commonservice.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.commonservice.service.port }}
          resources:
            {{- with .Values.commonservice.resources }}
            requests:
              {{- toYaml .requests | nindent 14 }}
            limits:
              {{- toYaml .limits | nindent 14 }}
            {{- end }}
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "file:{{ .Values.commonservice.config.mountPath }}/"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mysql
                  key: mysql-password
            - name: SPRING_FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mysql
                  key: mysql-root-password
          volumeMounts:
            - name: {{ .Values.commonservice.config.name }}
              mountPath: {{ .Values.commonservice.config.mountPath }}
              readOnly: true
      volumes:
        - name: {{ .Values.commonservice.config.name }}
          configMap:
            name: {{ .Release.Name }}-config
            items:
              - key: application.properties
                path: application.properties
