CREATE TABLE IF NOT EXISTS `phone` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `number` VARCHAR(20) NOT NULL,
    `country_code` VARCHAR(3) DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `verified_at` DATETIME DEFAULT NULL,
    `expired_at` DATETIME DEFAULT NULL,
    `created_by` VARCHAR(100) NOT NULL,
    `updated_by` VARCHAR(100) NOT NULL
);