commonservice:
  replicaCount: 1
  image:
    repository: ghcr.io/kuntiarso/commonservice
    pullPolicy: IfNotPresent
    tag: "latest"
  imagePullSecrets:
    enabled: true
    name: ghcr-credentials
  service:
    type: ClusterIP
    port: 10001
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

# sub-chart values
mysql:
  enabled: true
  auth:
    username: appuser
    database: appk8s
  primary:
    persistence:
      enabled: true
      size: 1Gi
