commonservice:
  replicaCount: 2
  image:
    repository: ghcr.io/kuntiarso/commonservice
    pullPolicy: Always
    tag: "latest"
  imagePullSecrets:
    enabled: true
    name: ghcr-credentials
  service:
    type: ClusterIP
    port: 10001
  config:
    name: config
    mountPath: /app/config
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

# sub-chart values
mysql:
  enabled: true
  auth:
    username: appuser
    database: appk8s
  primary:
    service:
      type: NodePort
      nodePorts:
        mysql: 30036
    persistence:
      enabled: true
      size: 1Gi

flyway:
  image: flyway/flyway:latest
  config:
    name: flyway-config
    mountPath: /app/flyway-config
  