name: Build and Push Common Service as Docker Image

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'commonservice/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup java 21 temurin
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: temurin
      
      - name: Cache maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('commonservice/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      
      - name: Build service jar
        working-directory: commonservice
        run: ./mvnw clean package -DskipTests
      
      - name: Login to docker-hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      
      - name: Build and push docker image
        env:
          IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/commonservice
        run: |
          TAG=${GITHUB_SHA::8}
          # build using the multi-stage Dockerfile in commonservice/
          docker build -t $IMAGE_NAME:$TAG commonservice/
          docker push $IMAGE_NAME:$TAG
          # also tag as latest
          docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
      
      - name: Cleanup old images (keep latest + current)
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PAT: ${{ secrets.DOCKERHUB_PAT }}
        run: |
          IMAGE_NAME=commonservice
          CURRENT_TAG=${GITHUB_SHA::8}
          echo "Fetching tags for cleanup..."

          TAGS=$(curl -s -u "$DOCKERHUB_USERNAME:$DOCKERHUB_PAT" \
            "https://hub.docker.com/repository/docker/$DOCKERHUB_USERNAME/$IMAGE_NAME/tags?page_size=100" \
            | jq -r '.results[].name' | grep -v '^latest$' | grep -v "^$CURRENT_TAG$")

          for tag in $TAGS; do
            echo "Deleting tag: $tag"
            curl -s -X DELETE -u "$DOCKERHUB_USERNAME:$DOCKERHUB_PAT" \
              "https://hub.docker.com/repository/docker/$DOCKERHUB_USERNAME/$IMAGE_NAME/tags/$tag/"
          done
          